### ISSUE TITLE
Pick&place: add new editor

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1569]
When adding the new editor, we need to make sure:
- [ ] play audio onCorrect/onIncorrect: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1429
- [ ] allow to trigger summatively only when all Pick&place augmentations in the step are correctly placed: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1427
- [ ] integrate sketchfab model selection (= move the button from the Arrow into the UI): https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1324
- [ ] think about how to do proximity based feedback: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1448
