### ISSUE TITLE
UX/UI: UX10: Pick&place improvments

### ISSUE THREAD

**Issue by fwild** [WEKIT-ECS/MIRAGE-XR#1880]
Pick & place improvements:

- [ ] Just place: no picking up of object, just use tap/air-tap to place)
- [ ] different shaped target zones (e.g. ghost target position visible/invisible, snap when close): https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1865
- [ ] optional submission button (“submit”): https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1676
- [ ] different triggers (collision, grab, ...): https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1628 and https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1613 and https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1613 and https://github.com/WEKIT-ECS/MIRAGE-XR/issues/827
- [ ] link with AI manager, to inject user actions into the conversation: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1964
- [ ] add state machine to link up multiple 'interactions' with events: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1427
- [ ] provide feedback scores: https://github.com/WEKIT-ECS/MIRAGE-XR/issues/806

**Comment by fwild** [comment]
Here is some inspiration from XR2learn's interact toolkit (for VR): https://github.com/XR2Learn/enabler-interact?tab=readme-ov-file
